[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "libuuid", "python3"]
aptPkgs = [
  "libcairo2-dev",
  "libpango1.0-dev",
  "libjpeg-dev",
  "libgif-dev",
  "libpng-dev",
  "librsvg2-dev",
  "libwebp-dev",
  "libfontconfig1-dev",
  "fonts-dejavu-core",
  "fonts-noto-color-emoji",
  "build-essential",
  "pkg-config",
  "libtool",
  "autoconf",
  "automake"
]

[phases.build]
cmds = [
  "fc-cache -fv",
  "npm ci --omit=dev",
  "mkdir -p emojis"
]

[start]
cmd = "node index.js"
